version: '3.9'

services:
  api:
    container_name: api
    restart: "no"
    build:
      context: .
      args:
        - DJANGO_SETTINGS_MODULE=app.settings.docker
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app/
    working_dir: /app
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - db
      - redis
      
  db:
    container_name: db
    image: postgres:15.6-alpine
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
