version: "3.9"

services:
  api:
    container_name: fastapi
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      PYTHONDONTWRITEBYTECODE: 1
    env_file:
      - .env
    depends_on:
      - postgresql

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql